#!/bin/bash

# This hook runs before npm install during EAS Build
# It patches the gradle configuration to support 16KB page size

echo "🔧 Configuring 16KB page size support..."

# This will be applied during the build process
# The actual gradle files will be generated by Expo, then we'll patch them

exit 0
